spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql:localhost:5432/phonebook_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.gara: DEBUG