spring:
  datasource:
    url: ${MYSQLDB_URL:jdbc:mysql://localhost:3345/phonebook_db}
    username: ${MYSQLDB_USER:root}
    password: ${MYSQLDB_ROOT_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SPRING_DOCKER_PORT:8080}

logging:
  level:
    root: INFO
    com.gara: DEBUG