kind: Service
apiVersion: v1
metadata:
  name: backendsvc
  namespace: phonebook-app
spec:
  selector:
    app: phonebook-backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
